name: add-finnhub-secret

on:
  workflow_dispatch:

env:
  APP_NAME: cja-mvc-demoproj
  RG_NAME: rg-cja-mvc-demoproj-eastus2

jobs:
  add-secret:
    runs-on: ubuntu-latest
    steps:
      - name: Azure Login
        uses: azure/login@v1
        with:
          creds: ${{ secrets.AZURE_CREDENTIALS }}

      - name: Add Finnhub API Key to Key Vault
        run: |
          az keyvault secret set \
            --vault-name ${APP_NAME}-kv \
            --name Finnhub-ApiKey \
            --value "${{ secrets.FINNHUB_API_KEY }}"
