name: sql-allow-webapp

on:
  workflow_dispatch:

env:
  APP_NAME: cja-mvc-demoproj
  RG_NAME: rg-cja-mvc-demoproj-eastus2

jobs:
  allow-webapp:
    runs-on: ubuntu-latest
    steps:
      - name: Azure Login
        uses: azure/login@v1
        with:
          creds: ${{ secrets.AZURE_CREDENTIALS }}

      - name: Get Web App outbound IPs
        id: ips
        run: |
          ips=$(az webapp show -g $RG_NAME -n $APP_NAME --query outboundIpAddresses -o tsv)
          echo "ips=$ips" >> $GITHUB_OUTPUT
          echo "Outbound IPs: $ips"

      - name: Create firewall rules for Web App IPs
        run: |
          for ip in $(echo "${{ steps.ips.outputs.ips }}" | tr ',' ' ')
          do
            echo "Adding firewall rule for $ip"
            az sql server firewall-rule create \
              -g $RG_NAME \
              -s ${APP_NAME}-sql \
              -n AllowWebApp-${ip//./-} \
              --start-ip-address $ip \
              --end-ip-address $ip
          done
